import type { VehicleSpecs } from "./types";

export type SeedDealer = {
  id: string;
  name: string;
  city: string;
  province: string;
  brands: string;
  website_url: string;
  inventory_url: string;
  /** Primary amalgamation pool when true (admin can toggle later). */
  active: boolean;
};

export type SeedVehicle = {
  external_id: string;
  dealership_id: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  body_style: string;
  exterior_color: string;
  interior_color: string;
  mileage: number;
  price_cents: number;
  vin: string;
  stock_number: string;
  description: string;
  specs: VehicleSpecs;
  thumbnail: string;
  photos: string[];
  listing_path: string;
};

export const DEALERS: SeedDealer[] = [
  {
    id: "pfaff-porsche",
    name: "Pfaff Porsche",
    city: "Vaughan",
    province: "ON",
    brands: "Porsche",
    website_url: "https://www.pfaffauto.com",
    inventory_url: "https://www.pfaffauto.com/inventory",
    active: true,
  },
  {
    id: "mark-motors-ottawa",
    name: "Mark Motors of Ottawa",
    city: "Ottawa",
    province: "ON",
    brands: "Porsche, Audi",
    website_url: "https://www.markmotors.com",
    inventory_url: "https://www.markmotors.com/inventory",
    active: false,
  },
  {
    id: "bmw-toronto",
    name: "BMW Toronto",
    city: "Toronto",
    province: "ON",
    brands: "BMW",
    website_url: "https://www.bmwtoronto.ca",
    inventory_url: "https://www.bmwtoronto.ca/inventory",
    active: false,
  },
  {
    id: "mb-vancouver",
    name: "Mercedes-Benz Downtown Vancouver",
    city: "Vancouver",
    province: "BC",
    brands: "Mercedes-Benz, AMG",
    website_url: "https://www.mbvancouver.ca",
    inventory_url: "https://www.mbvancouver.ca/inventory",
    active: false,
  },
  {
    id: "audi-stefoy",
    name: "Audi Ste-Foy",
    city: "Québec City",
    province: "QC",
    brands: "Audi",
    website_url: "https://www.audistefoy.ca",
    inventory_url: "https://www.audistefoy.ca/inventory",
    active: false,
  },
  {
    id: "jlr-toronto",
    name: "Jaguar Land Rover Toronto",
    city: "Toronto",
    province: "ON",
    brands: "Jaguar, Land Rover, Range Rover",
    website_url: "https://www.jlrtoronto.ca",
    inventory_url: "https://www.jlrtoronto.ca/inventory",
    active: false,
  },
  {
    id: "ferrari-ontario",
    name: "Ferrari of Ontario",
    city: "Woodbridge",
    province: "ON",
    brands: "Ferrari",
    website_url: "https://www.ferrari.com/en-CA/dealers/ferrari-of-ontario",
    inventory_url: "https://www.ferrari.com/en-CA/dealers/ferrari-of-ontario/inventory",
    active: true,
  },
  {
    id: "lambo-montreal",
    name: "Lamborghini Montréal",
    city: "Montréal",
    province: "QC",
    brands: "Lamborghini",
    website_url: "https://www.lamborghinimontreal.com",
    inventory_url: "https://www.lamborghinimontreal.com/inventory",
    active: true,
  },
  {
    id: "mclaren-toronto",
    name: "McLaren Toronto",
    city: "Toronto",
    province: "ON",
    brands: "McLaren",
    website_url: "https://toronto.mclaren.com",
    inventory_url: "https://toronto.mclaren.com/en/stock",
    active: false,
  },
  {
    id: "rr-vancouver",
    name: "Rolls-Royce Motor Cars Vancouver",
    city: "Vancouver",
    province: "BC",
    brands: "Rolls-Royce",
    website_url: "https://www.rolls-roycemotorcars-vancouver.com",
    inventory_url: "https://www.rolls-roycemotorcars-vancouver.com/inventory",
    active: false,
  },
  {
    id: "aston-montreal",
    name: "Aston Martin Montréal",
    city: "Montréal",
    province: "QC",
    brands: "Aston Martin",
    website_url: "https://www.astonmartinmontreal.com",
    inventory_url: "https://www.astonmartinmontreal.com/inventory",
    active: true,
  },
  {
    id: "bentley-toronto",
    name: "Bentley Toronto",
    city: "Toronto",
    province: "ON",
    brands: "Bentley",
    website_url: "https://www.bentleytoronto.com",
    inventory_url: "https://www.bentleytoronto.com/inventory",
    active: false,
  },
];

const IMG = {
  porsche: "/vehicles/top-porsche-911.jpg",
  taycan: "/vehicles/top-porsche-taycan.jpg",
  urus: "/vehicles/top-urus.jpg",
  ferrari: "/vehicles/top-ferrari-purosangue.jpg",
  ferrari458: "/vehicles/top-ferrari-458.jpg",
  ferrariWhite: "/vehicles/top-ferrari-purosangue.jpg",
  bentley: "/vehicles/top-bentley.jpg",
  mercedes: "/vehicles/top-porsche-911.jpg",
  bmw: "/vehicles/top-porsche-911.jpg",
  rolls: "/vehicles/top-rolls-spectre.jpg",
  rollsGhost: "/vehicles/top-rolls-spectre.jpg",
  mclaren: "/vehicles/top-mclaren.jpg",
  range: "/vehicles/top-urus.jpg",
  aston: "/vehicles/top-bentley.jpg",
};

/** Baseline catalog — crawler re-reads this feed and can mutate subset each run. */
export const BASE_INVENTORY: SeedVehicle[] = [
  {
    external_id: "PFA-911-TS-2401",
    dealership_id: "pfaff-porsche",
    year: 2024,
    make: "Porsche",
    model: "911",
    trim: "Turbo S",
    body_style: "Coupe",
    exterior_color: "Black",
    interior_color: "Black / Chalk",
    mileage: 1840,
    price_cents: 32990000,
    vin: "WP0AD2A99RS256401",
    stock_number: "P2401",
    description:
      "Near-new Turbo S with Sport Chrono, rear-axle steering, and Burmester High-End 3D Sound. Delivery-mileage feel with full factory warranty remaining.",
    specs: {
      engine: "3.8L Twin-Turbo Flat-6",
      transmission: "8-speed PDK",
      drivetrain: "AWD",
      horsepower: "640 hp",
      fuel: "Premium",
      seats: "4",
      doors: "2",
    },
    thumbnail: IMG.porsche,
    photos: [IMG.porsche],
    listing_path: "/inventory/2024-porsche-911-turbo-s",
  },
  {
    external_id: "PFA-CAY-GT-2312",
    dealership_id: "pfaff-porsche",
    year: 2023,
    make: "Porsche",
    model: "Cayenne",
    trim: "Turbo GT",
    body_style: "SUV",
    exterior_color: "Arctic Grey",
    interior_color: "Black/Bordeaux",
    mileage: 9200,
    price_cents: 24850000,
    vin: "WP1AF2AY5PDA12345",
    stock_number: "P2312",
    description:
      "Track-capable Cayenne Turbo GT with carbon package and ceramic composite brakes. One owner, full service history at Pfaff.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      transmission: "8-speed Tiptronic",
      drivetrain: "AWD",
      horsepower: "650 hp",
      fuel: "Premium",
      seats: "5",
      doors: "5",
    },
    thumbnail: IMG.range,
    photos: [IMG.range],
    listing_path: "/inventory/2023-porsche-cayenne-turbo-gt",
  },
  {
    external_id: "MMO-911-GTS-2411",
    dealership_id: "mark-motors-ottawa",
    year: 2024,
    make: "Porsche",
    model: "911",
    trim: "Carrera GTS",
    body_style: "Coupe",
    exterior_color: "Guards Red",
    interior_color: "Black",
    mileage: 4100,
    price_cents: 21490000,
    vin: "WP0AB2A99RS278901",
    stock_number: "M2411",
    description:
      "T-Hybrid GTS with Sport Design package. Mark Motors CPO inspection completed with remaining factory warranty.",
    specs: {
      engine: "3.6L Turbo Flat-6 Hybrid",
      transmission: "8-speed PDK",
      drivetrain: "RWD",
      horsepower: "532 hp",
      fuel: "Premium",
      seats: "4",
      doors: "2",
    },
    thumbnail: IMG.porsche,
    photos: [IMG.porsche],
    listing_path: "/inventory/2024-porsche-911-carrera-gts",
  },
  {
    external_id: "BMW-M8-COMP-2408",
    dealership_id: "bmw-toronto",
    year: 2024,
    make: "BMW",
    model: "M8",
    trim: "Competition Coupe",
    body_style: "Coupe",
    exterior_color: "Frozen Dark Grey",
    interior_color: "Merino Black",
    mileage: 6200,
    price_cents: 18990000,
    vin: "WBSGV0C09RCM12345",
    stock_number: "B2408",
    description:
      "M8 Competition with carbon exterior pack, Bowers & Wilkins Diamond Surround, and M Driver's Package.",
    specs: {
      engine: "4.4L Twin-Turbo V8",
      transmission: "8-speed M Steptronic",
      drivetrain: "AWD",
      horsepower: "617 hp",
      fuel: "Premium",
      seats: "4",
      doors: "2",
    },
    thumbnail: IMG.bmw,
    photos: [IMG.bmw],
    listing_path: "/inventory/2024-bmw-m8-competition",
  },
  {
    external_id: "BMW-X7-M60-2501",
    dealership_id: "bmw-toronto",
    year: 2025,
    make: "BMW",
    model: "X7",
    trim: "M60i",
    body_style: "SUV",
    exterior_color: "Mineral White",
    interior_color: "Cognac Vernasca",
    mileage: 890,
    price_cents: 16850000,
    vin: "5UX23EM09S9A12345",
    stock_number: "B2501",
    description:
      "Executive 7-seater with Executive Lounge seating, panoramic sky lounge, and M Sport Professional package.",
    specs: {
      engine: "4.4L Twin-Turbo V8 Mild Hybrid",
      transmission: "8-speed Steptronic",
      drivetrain: "xDrive AWD",
      horsepower: "523 hp",
      fuel: "Premium",
      seats: "7",
      doors: "5",
    },
    thumbnail: IMG.range,
    photos: [IMG.range],
    listing_path: "/inventory/2025-bmw-x7-m60i",
  },
  {
    external_id: "MBV-AMG-GT-63-2410",
    dealership_id: "mb-vancouver",
    year: 2024,
    make: "Mercedes-AMG",
    model: "GT",
    trim: "63 4MATIC+",
    body_style: "Coupe",
    exterior_color: "High-Tech Silver",
    interior_color: "Black Nappa",
    mileage: 3500,
    price_cents: 21400000,
    vin: "W1KYJ8FB9RA012345",
    stock_number: "V2410",
    description:
      "Second-generation AMG GT with handcrafted 4.0L biturbo V8, AMG Performance seats, and carbon ceramic brakes.",
    specs: {
      engine: "4.0L Biturbo V8",
      transmission: "9-speed MCT",
      drivetrain: "4MATIC+ AWD",
      horsepower: "577 hp",
      fuel: "Premium",
      seats: "4",
      doors: "2",
    },
    thumbnail: IMG.mercedes,
    photos: [IMG.mercedes],
    listing_path: "/inventory/2024-mercedes-amg-gt-63",
  },
  {
    external_id: "MBV-S580-2311",
    dealership_id: "mb-vancouver",
    year: 2023,
    make: "Mercedes-Benz",
    model: "S-Class",
    trim: "S 580 4MATIC",
    body_style: "Sedan",
    exterior_color: "Obsidian Black",
    interior_color: "Macchiato Beige",
    mileage: 11800,
    price_cents: 15690000,
    vin: "W1K6G7GB5PA123456",
    stock_number: "V2311",
    description:
      "Flagship S 580 with Executive Rear Package, Burmester 4D, and rear-axle steering. Concierge-maintained.",
    specs: {
      engine: "4.0L Twin-Turbo V8 Mild Hybrid",
      transmission: "9G-TRONIC",
      drivetrain: "4MATIC AWD",
      horsepower: "496 hp",
      fuel: "Premium",
      seats: "5",
      doors: "4",
    },
    thumbnail: IMG.rolls,
    photos: [IMG.rolls],
    listing_path: "/inventory/2023-mercedes-s580",
  },
  {
    external_id: "ASF-RS7-2406",
    dealership_id: "audi-stefoy",
    year: 2024,
    make: "Audi",
    model: "RS 7",
    trim: "Performance",
    body_style: "Sedan",
    exterior_color: "Nardo Grey",
    interior_color: "Black Dinamica",
    mileage: 5400,
    price_cents: 17250000,
    vin: "WUAPBAF28RN901234",
    stock_number: "Q2406",
    description:
      "RS 7 Performance with carbon optic package, RS sport exhaust, and Bang & Olufsen 3D sound.",
    specs: {
      engine: "4.0L Twin-Turbo V8 TFSI",
      transmission: "8-speed tiptronic",
      drivetrain: "quattro AWD",
      horsepower: "621 hp",
      fuel: "Premium",
      seats: "5",
      doors: "4",
    },
    thumbnail: IMG.bmw,
    photos: [IMG.bmw],
    listing_path: "/inventory/2024-audi-rs7-performance",
  },
  {
    external_id: "JLR-RR-SV-2502",
    dealership_id: "jlr-toronto",
    year: 2025,
    make: "Land Rover",
    model: "Range Rover",
    trim: "Autobiography P530",
    body_style: "SUV",
    exterior_color: "Charente Grey",
    interior_color: "Perlino / Ebony",
    mileage: 1200,
    price_cents: 26890000,
    vin: "SALKP9E49SA123456",
    stock_number: "J2502",
    description:
      "Long-wheelbase Autobiography with Executive Class rear seats, refrigerator compartment, and Meridian Signature Sound.",
    specs: {
      engine: "4.4L Twin-Turbo V8",
      transmission: "8-speed automatic",
      drivetrain: "AWD",
      horsepower: "523 hp",
      fuel: "Premium",
      seats: "5",
      doors: "5",
    },
    thumbnail: IMG.range,
    photos: [IMG.range],
    listing_path: "/inventory/2025-range-rover-autobiography",
  },
  {
    external_id: "JLR-FTYPE-R-2210",
    dealership_id: "jlr-toronto",
    year: 2022,
    make: "Jaguar",
    model: "F-TYPE",
    trim: "R Coupe",
    body_style: "Coupe",
    exterior_color: "Santorini Black",
    interior_color: "Ebony",
    mileage: 14500,
    price_cents: 11890000,
    vin: "SAJDB4BN9NCY12345",
    stock_number: "J2210",
    description:
      "Supercharged V8 F-TYPE R with Adaptive Dynamics and Configurable Dynamics. Rare low-mileage example under $150k.",
    specs: {
      engine: "5.0L Supercharged V8",
      transmission: "8-speed automatic",
      drivetrain: "AWD",
      horsepower: "575 hp",
      fuel: "Premium",
      seats: "2",
      doors: "2",
    },
    thumbnail: IMG.aston,
    photos: [IMG.aston],
    listing_path: "/inventory/2022-jaguar-ftype-r",
  },
  {
    external_id: "FER-ROMA-SP-2403",
    dealership_id: "ferrari-ontario",
    year: 2024,
    make: "Ferrari",
    model: "Roma",
    trim: "Spider",
    body_style: "Convertible",
    exterior_color: "Blu Tour de France",
    interior_color: "Cuoio",
    mileage: 980,
    price_cents: 39850000,
    vin: "ZFF09RHT0R0298123",
    stock_number: "F2403",
    description:
      "Roma Spider with carbon fibre driver zone, Magneride dual-mode suspension, and full Ferrari Approved coverage.",
    specs: {
      engine: "3.9L Twin-Turbo V8",
      transmission: "8-speed DCT",
      drivetrain: "RWD",
      horsepower: "612 hp",
      fuel: "Premium",
      seats: "2+2",
      doors: "2",
    },
    thumbnail: IMG.ferrariWhite,
    photos: [IMG.ferrariWhite],
    listing_path: "/inventory/2024-ferrari-roma-spider",
  },
  {
    external_id: "FER-296-GTB-2310",
    dealership_id: "ferrari-ontario",
    year: 2023,
    make: "Ferrari",
    model: "296",
    trim: "GTB",
    body_style: "Coupe",
    exterior_color: "Rosso Corsa",
    interior_color: "Nero",
    mileage: 2100,
    price_cents: 44900000,
    vin: "ZFF99SLA0P0294567",
    stock_number: "F2310",
    description:
      "Plug-in hybrid V6 with Assetto Fiorano package. Instant torque delivery and track telemetry package included.",
    specs: {
      engine: "3.0L Twin-Turbo V6 + Electric",
      transmission: "8-speed DCT",
      drivetrain: "RWD",
      horsepower: "818 hp combined",
      fuel: "Hybrid",
      seats: "2",
      doors: "2",
    },
    thumbnail: IMG.ferrari,
    photos: [IMG.ferrari],
    listing_path: "/inventory/2023-ferrari-296-gtb",
  },
  {
    external_id: "LAM-URUS-PERF-2412",
    dealership_id: "lambo-montreal",
    year: 2024,
    make: "Lamborghini",
    model: "Urus",
    trim: "Performante",
    body_style: "SUV",
    exterior_color: "Bianco Icarus",
    interior_color: "Nero Ade / Giallo Taurus",
    mileage: 2700,
    price_cents: 38990000,
    vin: "ZPBUA1ZL9RLA12345",
    stock_number: "L2412",
    description:
      "Urus Performante with carbon roof, lightweight package, and Akrapovič exhaust. Montréal delivery available.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      transmission: "8-speed automatic",
      drivetrain: "AWD",
      horsepower: "657 hp",
      fuel: "Premium",
      seats: "5",
      doors: "5",
    },
    thumbnail: IMG.urus,
    photos: [IMG.urus],
    listing_path: "/inventory/2024-lamborghini-urus-performante",
  },
  {
    external_id: "LAM-HUR-EVO-2205",
    dealership_id: "lambo-montreal",
    year: 2022,
    make: "Lamborghini",
    model: "Huracán",
    trim: "EVO RWD",
    body_style: "Coupe",
    exterior_color: "Verde Mantis",
    interior_color: "Nero Ade",
    mileage: 6800,
    price_cents: 28950000,
    vin: "ZHWUF4ZF9NLA67890",
    stock_number: "L2205",
    description:
      "Naturally aspirated V10 EVO RWD with Lifting System and Branding Package. Serviced exclusively at Lamborghini Montréal.",
    specs: {
      engine: "5.2L V10",
      transmission: "7-speed dual-clutch",
      drivetrain: "RWD",
      horsepower: "610 hp",
      fuel: "Premium",
      seats: "2",
      doors: "2",
    },
    thumbnail: IMG.mclaren,
    photos: [IMG.mclaren],
    listing_path: "/inventory/2022-lamborghini-huracan-evo",
  },
  {
    external_id: "MCL-720S-2309",
    dealership_id: "mclaren-toronto",
    year: 2023,
    make: "McLaren",
    model: "720S",
    trim: "Performance",
    body_style: "Coupe",
    exterior_color: "Papaya Spark",
    interior_color: "Carbon Black",
    mileage: 3200,
    price_cents: 34200000,
    vin: "SBM14DCA0PW001234",
    stock_number: "M2309",
    description:
      "720S Performance with electrochromic roof, MSO Defined paint, and Bowers & Wilkins audio.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      transmission: "7-speed SSG",
      drivetrain: "RWD",
      horsepower: "710 hp",
      fuel: "Premium",
      seats: "2",
      doors: "2",
    },
    thumbnail: IMG.mclaren,
    photos: [IMG.mclaren],
    listing_path: "/inventory/2023-mclaren-720s",
  },
  {
    external_id: "MCL-ARTURA-2407",
    dealership_id: "mclaren-toronto",
    year: 2024,
    make: "McLaren",
    model: "Artura",
    trim: "Coupe",
    body_style: "Coupe",
    exterior_color: "Flux Green",
    interior_color: "Carbon Black",
    mileage: 1500,
    price_cents: 29850000,
    vin: "SBM15TAA0RW005678",
    stock_number: "M2407",
    description:
      "Plug-in hybrid Artura with Clubsport seats and Sports Exhaust. Low kilometres, full McLaren warranty.",
    specs: {
      engine: "3.0L Twin-Turbo V6 Hybrid",
      transmission: "8-speed dual-clutch",
      drivetrain: "RWD",
      horsepower: "671 hp combined",
      fuel: "Hybrid",
      seats: "2",
      doors: "2",
    },
    thumbnail: IMG.mclaren,
    photos: [IMG.mclaren],
    listing_path: "/inventory/2024-mclaren-artura",
  },
  {
    external_id: "RRV-GHOST-2411",
    dealership_id: "rr-vancouver",
    year: 2024,
    make: "Rolls-Royce",
    model: "Ghost",
    trim: "Black Badge",
    body_style: "Sedan",
    exterior_color: "Black Diamond",
    interior_color: "Arctic White / Black",
    mileage: 2100,
    price_cents: 51200000,
    vin: "SCA664S52RUX12345",
    stock_number: "R2411",
    description:
      "Black Badge Ghost with illuminated fascia, rear theatre configuration, and starlight headliner. West Coast delivery.",
    specs: {
      engine: "6.75L Twin-Turbo V12",
      transmission: "8-speed automatic",
      drivetrain: "AWD",
      horsepower: "591 hp",
      fuel: "Premium",
      seats: "5",
      doors: "4",
    },
    thumbnail: IMG.rolls,
    photos: [IMG.rolls],
    listing_path: "/inventory/2024-rolls-royce-ghost-black-badge",
  },
  {
    external_id: "RRV-CULLINAN-2306",
    dealership_id: "rr-vancouver",
    year: 2023,
    make: "Rolls-Royce",
    model: "Cullinan",
    trim: "Black Badge",
    body_style: "SUV",
    exterior_color: "Tempest Grey",
    interior_color: "Seashell / Black",
    mileage: 8900,
    price_cents: 54800000,
    vin: "SCA687S54PUX67890",
    stock_number: "R2306",
    description:
      "Cullinan Black Badge with viewing suite, picnic tables, and Bespoke Audio. One principal owner.",
    specs: {
      engine: "6.75L Twin-Turbo V12",
      transmission: "8-speed automatic",
      drivetrain: "AWD",
      horsepower: "591 hp",
      fuel: "Premium",
      seats: "5",
      doors: "5",
    },
    thumbnail: IMG.range,
    photos: [IMG.range, IMG.rolls],
    listing_path: "/inventory/2023-rolls-royce-cullinan",
  },
  {
    external_id: "AM-DB12-2404",
    dealership_id: "aston-montreal",
    year: 2024,
    make: "Aston Martin",
    model: "DB12",
    trim: "Coupe",
    body_style: "Coupe",
    exterior_color: "Silver Birch",
    interior_color: "Obsidian Black",
    mileage: 1600,
    price_cents: 31890000,
    vin: "SCFRMFAW0RGS12345",
    stock_number: "A2404",
    description:
      "DB12 Coupe with Comfort & Technology Pack, carbon fibre roof, and 800W Bowers & Wilkins system.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      transmission: "8-speed automatic",
      drivetrain: "RWD",
      horsepower: "671 hp",
      fuel: "Premium",
      seats: "2+2",
      doors: "2",
    },
    thumbnail: IMG.aston,
    photos: [IMG.aston],
    listing_path: "/inventory/2024-aston-martin-db12",
  },
  {
    external_id: "AM-DBX707-2312",
    dealership_id: "aston-montreal",
    year: 2023,
    make: "Aston Martin",
    model: "DBX",
    trim: "707",
    body_style: "SUV",
    exterior_color: "Magnetic Silver",
    interior_color: "Oxford Tan",
    mileage: 7400,
    price_cents: 27850000,
    vin: "SCFVMGAW0PGS67890",
    stock_number: "A2312",
    description:
      "DBX707 — the most powerful luxury SUV from Gaydon. Carbon ceramic brakes and 23-inch forged wheels.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      transmission: "9-speed automatic",
      drivetrain: "AWD",
      horsepower: "697 hp",
      fuel: "Premium",
      seats: "5",
      doors: "5",
    },
    thumbnail: IMG.urus,
    photos: [IMG.urus, IMG.aston],
    listing_path: "/inventory/2023-aston-martin-dbx-707",
  },
  {
    external_id: "BEN-CGT-S-2410",
    dealership_id: "bentley-toronto",
    year: 2024,
    make: "Bentley",
    model: "Continental GT",
    trim: "Speed",
    body_style: "Coupe",
    exterior_color: "British Racing Green",
    interior_color: "Linen / Cumbrian Green",
    mileage: 2200,
    price_cents: 36890000,
    vin: "SCBCT2ZG0RCX12345",
    stock_number: "BT2410",
    description:
      "Continental GT Speed with rotating display, Naim for Bentley audio, and diamond-quilted hides.",
    specs: {
      engine: "6.0L Twin-Turbo W12",
      transmission: "8-speed dual-clutch",
      drivetrain: "AWD",
      horsepower: "650 hp",
      fuel: "Premium",
      seats: "4",
      doors: "2",
    },
    thumbnail: IMG.bentley,
    photos: [IMG.bentley],
    listing_path: "/inventory/2024-bentley-continental-gt-speed",
  },
  {
    external_id: "BEN-FLY-AZURE-2501",
    dealership_id: "bentley-toronto",
    year: 2025,
    make: "Bentley",
    model: "Flying Spur",
    trim: "Azure",
    body_style: "Sedan",
    exterior_color: "Glacier White",
    interior_color: "Hotspur / Beluga",
    mileage: 450,
    price_cents: 41250000,
    vin: "SCBBS6ZG0SCX67890",
    stock_number: "BT2501",
    description:
      "Flying Spur Azure with rear-seat entertainment, mood lighting suite, and Mulliner Driving Specification.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      transmission: "8-speed dual-clutch",
      drivetrain: "AWD",
      horsepower: "542 hp",
      fuel: "Premium",
      seats: "5",
      doors: "4",
    },
    thumbnail: IMG.bentley,
    photos: [IMG.bentley, IMG.rolls],
    listing_path: "/inventory/2025-bentley-flying-spur-azure",
  },
  {
    external_id: "PFA-TAY-TURBO-S-2211",
    dealership_id: "pfaff-porsche",
    year: 2022,
    make: "Porsche",
    model: "Taycan",
    trim: "Turbo S",
    body_style: "Sedan",
    exterior_color: "Frozen Blue Metallic",
    interior_color: "Black / Chalk",
    mileage: 16200,
    price_cents: 13990000,
    vin: "WP0AH2Y19NSA12345",
    stock_number: "P2211",
    description:
      "All-electric Turbo S with Performance Battery Plus, rear-axle steering, and Porsche InnoDrive. Under the premium threshold for a sharp lease entry.",
    specs: {
      engine: "Dual Permanent Magnet Motors",
      transmission: "2-speed rear / 1-speed front",
      drivetrain: "AWD",
      horsepower: "750 hp overboost",
      fuel: "Electric",
      seats: "4",
      doors: "4",
    },
    thumbnail: IMG.taycan,
    photos: [IMG.taycan],
    listing_path: "/inventory/2022-porsche-taycan-turbo-s",
  },
  {
    external_id: "MBV-G63-2402",
    dealership_id: "mb-vancouver",
    year: 2024,
    make: "Mercedes-AMG",
    model: "G 63",
    trim: "4MATIC",
    body_style: "SUV",
    exterior_color: "Manufactur Magno Night Black",
    interior_color: "Classic Red / Black Nappa",
    mileage: 4800,
    price_cents: 27890000,
    vin: "W1NYC7HJ5RX123456",
    stock_number: "V2402",
    description:
      "Iconic G 63 with Active Curve System, Burmester 3D, and Exclusive Interior Plus. Instant recognition factor.",
    specs: {
      engine: "4.0L Biturbo V8 Mild Hybrid",
      transmission: "9G-TRONIC",
      drivetrain: "4MATIC AWD",
      horsepower: "577 hp",
      fuel: "Premium",
      seats: "5",
      doors: "5",
    },
    thumbnail: IMG.urus,
    photos: [IMG.urus, IMG.mercedes],
    listing_path: "/inventory/2024-mercedes-amg-g63",
  },
];

/** Rotating “new arrival” pool the crawler may introduce on a run. */
export const ROTATING_ARRIVALS: SeedVehicle[] = [
  {
    external_id: "FER-PUROSANGUE-2503",
    dealership_id: "ferrari-ontario",
    year: 2025,
    make: "Ferrari",
    model: "Purosangue",
    trim: "V12",
    body_style: "SUV",
    exterior_color: "Grigio Silverstone",
    interior_color: "Bordeaux",
    mileage: 320,
    price_cents: 59800000,
    vin: "ZFF27TMA0S0299999",
    stock_number: "F2503",
    description:
      "Just landed: Purosangue V12 with carbon roof and rear-hinged doors. Ultra-limited allocation.",
    specs: {
      engine: "6.5L Naturally Aspirated V12",
      transmission: "8-speed dual-clutch",
      drivetrain: "AWD",
      horsepower: "715 hp",
      fuel: "Premium",
      seats: "4",
      doors: "4",
    },
    thumbnail: IMG.ferrari,
    photos: [IMG.ferrari, IMG.range],
    listing_path: "/inventory/2025-ferrari-purosangue",
  },
  {
    external_id: "LAM-REVUELTO-2501",
    dealership_id: "lambo-montreal",
    year: 2025,
    make: "Lamborghini",
    model: "Revuelto",
    trim: "Coupe",
    body_style: "Coupe",
    exterior_color: "Arancio Borealis",
    interior_color: "Nero Ade",
    mileage: 180,
    price_cents: 72500000,
    vin: "ZHWUA4ZF9SLA11111",
    stock_number: "L2501",
    description:
      "Hybrid V12 flagship with 1,001 hp combined. First Canadian retail allocation at Lamborghini Montréal.",
    specs: {
      engine: "6.5L V12 + 3 Electric Motors",
      transmission: "8-speed dual-clutch",
      drivetrain: "AWD",
      horsepower: "1,001 hp combined",
      fuel: "Hybrid",
      seats: "2",
      doors: "2",
    },
    thumbnail: IMG.mclaren,
    photos: [IMG.mclaren, IMG.urus],
    listing_path: "/inventory/2025-lamborghini-revuelto",
  },
  {
    external_id: "RRV-SPECTRE-2412",
    dealership_id: "rr-vancouver",
    year: 2024,
    make: "Rolls-Royce",
    model: "Spectre",
    trim: "Coupe",
    body_style: "Coupe",
    exterior_color: "Midnight Sapphire",
    interior_color: "Grace White",
    mileage: 900,
    price_cents: 58900000,
    vin: "SCA1S6ZE0RUXaaaaa",
    stock_number: "R2412",
    description:
      "All-electric Spectre with starlight doors and illuminated grille. Whisper-quiet grand touring.",
    specs: {
      engine: "Dual Electric Motors",
      transmission: "Single-speed",
      drivetrain: "AWD",
      horsepower: "577 hp",
      fuel: "Electric",
      seats: "4",
      doors: "2",
    },
    thumbnail: IMG.rolls,
    photos: [IMG.rolls],
    listing_path: "/inventory/2024-rolls-royce-spectre",
  },
];

export function slugifyVehicle(v: Pick<SeedVehicle, "year" | "make" | "model" | "trim" | "external_id">): string {
  const base = [v.year, v.make, v.model, v.trim, v.external_id]
    .join(" ")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return base;
}

export function dealerListingUrl(dealerId: string, listingPath: string): string {
  const dealer = DEALERS.find((d) => d.id === dealerId);
  if (!dealer) return listingPath;
  try {
    return new URL(listingPath.replace(/^\//, ""), dealer.inventory_url.endsWith("/")
      ? dealer.inventory_url
      : dealer.inventory_url + "/").toString();
  } catch {
    return `${dealer.inventory_url}${listingPath.startsWith("/") ? "" : "/"}${listingPath}`;
  }
}
