/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaseSlugRouteImport } from './routes/lease/$slug'
import { Route as PortalClientRouteImport } from './routes/portal/client'
import { Route as PortalDealerRouteImport } from './routes/portal/dealer'
import { Route as ApiAdminCrawlRouteImport } from './routes/api/admin/crawl'
import { Route as ApiAdminMailRouteImport } from './routes/api/admin/mail'
import { Route as ApiAdminRerenderRouteImport } from './routes/api/admin/rerender'
import { Route as ApiAdminThumbsRouteImport } from './routes/api/admin/thumbs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronCrawlRouteImport } from './routes/api/cron/crawl'
import { Route as ApiThumbIdRouteImport } from './routes/api/thumb.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaseSlugRoute = LeaseSlugRouteImport.update({
  id: '/lease/$slug',
  path: '/lease/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalClientRoute = PortalClientRouteImport.update({
  id: '/portal/client',
  path: '/portal/client',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDealerRoute = PortalDealerRouteImport.update({
  id: '/portal/dealer',
  path: '/portal/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCrawlRoute = ApiAdminCrawlRouteImport.update({
  id: '/api/admin/crawl',
  path: '/api/admin/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMailRoute = ApiAdminMailRouteImport.update({
  id: '/api/admin/mail',
  path: '/api/admin/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRerenderRoute = ApiAdminRerenderRouteImport.update({
  id: '/api/admin/rerender',
  path: '/api/admin/rerender',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminThumbsRoute = ApiAdminThumbsRouteImport.update({
  id: '/api/admin/thumbs',
  path: '/api/admin/thumbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCrawlRoute = ApiCronCrawlRouteImport.update({
  id: '/api/cron/crawl',
  path: '/api/cron/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThumbIdRoute = ApiThumbIdRouteImport.update({
  id: '/api/thumb/$id',
  path: '/api/thumb/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/lease/$slug': typeof LeaseSlugRoute
  '/portal/client': typeof PortalClientRoute
  '/portal/dealer': typeof PortalDealerRoute
  '/api/admin/crawl': typeof ApiAdminCrawlRoute
  '/api/admin/mail': typeof ApiAdminMailRoute
  '/api/admin/rerender': typeof ApiAdminRerenderRoute
  '/api/admin/thumbs': typeof ApiAdminThumbsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
  '/api/thumb/$id': typeof ApiThumbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/lease/$slug': typeof LeaseSlugRoute
  '/portal/client': typeof PortalClientRoute
  '/portal/dealer': typeof PortalDealerRoute
  '/api/admin/crawl': typeof ApiAdminCrawlRoute
  '/api/admin/mail': typeof ApiAdminMailRoute
  '/api/admin/rerender': typeof ApiAdminRerenderRoute
  '/api/admin/thumbs': typeof ApiAdminThumbsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
  '/api/thumb/$id': typeof ApiThumbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/lease/$slug': typeof LeaseSlugRoute
  '/portal/client': typeof PortalClientRoute
  '/portal/dealer': typeof PortalDealerRoute
  '/api/admin/crawl': typeof ApiAdminCrawlRoute
  '/api/admin/mail': typeof ApiAdminMailRoute
  '/api/admin/rerender': typeof ApiAdminRerenderRoute
  '/api/admin/thumbs': typeof ApiAdminThumbsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
  '/api/thumb/$id': typeof ApiThumbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/crm'
    | '/how-it-works'
    | '/inventory'
    | '/login'
    | '/lease/$slug'
    | '/portal/client'
    | '/portal/dealer'
    | '/api/admin/crawl'
    | '/api/admin/mail'
    | '/api/admin/rerender'
    | '/api/admin/thumbs'
    | '/api/auth/$'
    | '/api/cron/crawl'
    | '/api/thumb/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/crm'
    | '/how-it-works'
    | '/inventory'
    | '/login'
    | '/lease/$slug'
    | '/portal/client'
    | '/portal/dealer'
    | '/api/admin/crawl'
    | '/api/admin/mail'
    | '/api/admin/rerender'
    | '/api/admin/thumbs'
    | '/api/auth/$'
    | '/api/cron/crawl'
    | '/api/thumb/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crm'
    | '/how-it-works'
    | '/inventory'
    | '/login'
    | '/lease/$slug'
    | '/portal/client'
    | '/portal/dealer'
    | '/api/admin/crawl'
    | '/api/admin/mail'
    | '/api/admin/rerender'
    | '/api/admin/thumbs'
    | '/api/auth/$'
    | '/api/cron/crawl'
    | '/api/thumb/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CrmRoute: typeof CrmRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  LeaseSlugRoute: typeof LeaseSlugRoute
  PortalClientRoute: typeof PortalClientRoute
  PortalDealerRoute: typeof PortalDealerRoute
  ApiAdminCrawlRoute: typeof ApiAdminCrawlRoute
  ApiAdminMailRoute: typeof ApiAdminMailRoute
  ApiAdminRerenderRoute: typeof ApiAdminRerenderRoute
  ApiAdminThumbsRoute: typeof ApiAdminThumbsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronCrawlRoute: typeof ApiCronCrawlRoute
  ApiThumbIdRoute: typeof ApiThumbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lease/$slug': {
      id: '/lease/$slug'
      path: '/lease/$slug'
      fullPath: '/lease/$slug'
      preLoaderRoute: typeof LeaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/client': {
      id: '/portal/client'
      path: '/portal/client'
      fullPath: '/portal/client'
      preLoaderRoute: typeof PortalClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dealer': {
      id: '/portal/dealer'
      path: '/portal/dealer'
      fullPath: '/portal/dealer'
      preLoaderRoute: typeof PortalDealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/crawl': {
      id: '/api/admin/crawl'
      path: '/api/admin/crawl'
      fullPath: '/api/admin/crawl'
      preLoaderRoute: typeof ApiAdminCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mail': {
      id: '/api/admin/mail'
      path: '/api/admin/mail'
      fullPath: '/api/admin/mail'
      preLoaderRoute: typeof ApiAdminMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/rerender': {
      id: '/api/admin/rerender'
      path: '/api/admin/rerender'
      fullPath: '/api/admin/rerender'
      preLoaderRoute: typeof ApiAdminRerenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/thumbs': {
      id: '/api/admin/thumbs'
      path: '/api/admin/thumbs'
      fullPath: '/api/admin/thumbs'
      preLoaderRoute: typeof ApiAdminThumbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/crawl': {
      id: '/api/cron/crawl'
      path: '/api/cron/crawl'
      fullPath: '/api/cron/crawl'
      preLoaderRoute: typeof ApiCronCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumb/$id': {
      id: '/api/thumb/$id'
      path: '/api/thumb/$id'
      fullPath: '/api/thumb/$id'
      preLoaderRoute: typeof ApiThumbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CrmRoute: CrmRoute,
  HowItWorksRoute: HowItWorksRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  LeaseSlugRoute: LeaseSlugRoute,
  PortalClientRoute: PortalClientRoute,
  PortalDealerRoute: PortalDealerRoute,
  ApiAdminCrawlRoute: ApiAdminCrawlRoute,
  ApiAdminMailRoute: ApiAdminMailRoute,
  ApiAdminRerenderRoute: ApiAdminRerenderRoute,
  ApiAdminThumbsRoute: ApiAdminThumbsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronCrawlRoute: ApiCronCrawlRoute,
  ApiThumbIdRoute: ApiThumbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
